### ISSUE TITLE
need a repo for a Rails example project

### ISSUE THREAD

**Issue by noeldevelops** [thedigitalgarage/digitalgarage-docs#15]
This will be linked to in the documentation instead of Openshift's repo, in places like the following : http://docs.thedigitalgarage.io/getting_started/beyond_the_basics.html#btb-other-quickstarts

**Comment by johnmccawley** [comment]
- [x] forked repo for Ruby example repo from openshift
- [x] updated readme and hello world in forked repo
- [x] forked the ruby s2i repo from scl.org
- [x] created the s2i-ruby docker images on docker hub
- [x] updated the ruby qs template (qs-ruby-postgres) to build using Ruby 2.4.x and dockerhub.io/thedigital garage/s2i-ruby:2.4 image from dockerhub.
