### ISSUE TITLE
Remove reference to RHEL images in docs

### ISSUE THREAD

**Issue by johnmccawley** [thedigitalgarage/digitalgarage-docs#17]
http://docs.thedigitalgarage.io/using_images/s2i_images 

All of the images in this section reference Red Hat Enterprise Linux. Digital Garage is only supporting the CentOS 7 images for these s2i builders. We need to remove the reference to RHEL.

**Comment by noeldevelops** [comment]
finished removing RHEL references in s2i section of the docs as well as those in the README file for Jenkins repo
