### ISSUE TITLE
"Our Community" link needs to be updated to new URL for DGC

### ISSUE THREAD

**Issue by havanaposa** [thedigitalgarage/digitalgarage-docs#4]
<img width="1280" alt="7536849a-e2d3-11e6-97ff-7d37e015cff0" src="https://cloud.githubusercontent.com/assets/19932198/22298921/792a4a80-e2df-11e6-9059-21b4a911da5b.png">

the link for "Our Community" is still linked to the old DG community URL 

Thank you :)

**Comment by johnmccawley** [comment]
OK, I have the documentation files. I will update this today and redeploy tonight.

**Comment by johnmccawley** [comment]
Removed Privacy Policy, Terms of Use and repaired the link to Our Community
