### ISSUE TITLE
Link to landing page doesn't work

### ISSUE THREAD

**Issue by havanaposa** [thedigitalgarage/digitalgarage-docs#5]
<img width="1280" alt="screen shot 2017-01-27 at 9 01 15 am" src="https://cloud.githubusercontent.com/assets/19932198/22377448/3ac1d1fa-e46f-11e6-8d9b-c9691a289e81.png">
![Uploading Screen Shot 2017-01-27 at 9.01.17 AM.png…]()

**Comment by johnmccawley** [comment]
Hello @handmilkingsoftware , I will take this issue. I am familiar with the documentation and how it works.
